version: '3'

services:
  hellodoctor-discovery-server:
    container_name: hellodoctor-discovery-server_1
    image: tranngockhoa/hellodoctor-discovery-server
    networks:
      - hellodoctor-network
    ports:
      - ${DISCO_SERVER_PORT_TARGET}:${DISCO_SERVER_PORT_PUBLIS}
    entrypoint: ["./dockerize","-wait=tcp://hellodoctor-configserver:${CONFI_SERVER_PORT_PUBLIS}","-timeout=60s","--","java","-jar","hellodoctor-discovery-server.jar"]
    depends_on:
      - hellodoctor-configserver
    environment:
      DNS_CONFIG_SERVER: hellodoctor-configserver

  hellodoctor-api-gateway:
    container_name: hellodoctor-api-gateway_1
    image: tranngockhoa/hellodoctor-api-gateway
    networks:
      - hellodoctor-network
    ports:
      - ${GATEW_SERVER_PORT_TARGET}:${GATEW_SERVER_PORT_PUBLIS}
    entrypoint: ["./dockerize","-wait=tcp://hellodoctor-discovery-server:${DISCO_SERVER_PORT_PUBLIS}","-timeout=60s","--","java","-jar","hellodoctor-api-gateway.jar"]

    depends_on:
      - hellodoctor-configserver
      - hellodoctor-discovery-server
    environment:
      DNS_DISCOVERY_SERVER: hellodoctor-discovery-server
      SPRING_RABBITMQ_HOST: rabbitmq-server
      DNS_CONFIG_SERVER: hellodoctor-configserver

  hellodoctor-configserver:
    container_name: hellodoctor-configserver_1
    image: tranngockhoa/hellodoctor-configserver
    networks:
      - hellodoctor-network
    ports:
      - ${CONFI_SERVER_PORT_TARGET}:${CONFI_SERVER_PORT_PUBLIS}

  hellodoctor-booking-service:
    container_name: hellodoctor-booking-service_1
    image: tranngockhoa/hellodoctor-booking-service
    networks:
      - hellodoctor-network
    ports:
      - ${BOOKI_SERVIC_PORT_TARGET}:${BOOKI_SERVIC_PORT_PUBLIS}
    entrypoint: ["./dockerize","-wait=tcp://hellodoctor-discovery-server:${DISCO_SERVER_PORT_PUBLIS}","-timeout=60s","--","java","-jar","hellodoctor-booking-service.jar"]
    depends_on:
      - hellodoctor-configserver
      - hellodoctor-discovery-server
    environment:
      DNS_DISCOVERY_SERVER: hellodoctor-discovery-server
      DNS_CONFIG_SERVER: hellodoctor-configserver

  hellodoctor-location-service:
    container_name: hellodoctor-location-service_1
    image: tranngockhoa/hellodoctor-location-service
    networks:
      - hellodoctor-network
    ports:
      - ${LOCAT_SERVIC_PORT_TARGET}:${LOCAT_SERVIC_PORT_PUBLIS}
    entrypoint: ["./dockerize","-wait=tcp://hellodoctor-discovery-server:${DISCO_SERVER_PORT_PUBLIS}","-timeout=60s","--","java","-jar","hellodoctor-location-service.jar"]
    depends_on:
      - hellodoctor-configserver
      - hellodoctor-discovery-server
    environment:
      DNS_DISCOVERY_SERVER: hellodoctor-discovery-server
      DNS_CONFIG_SERVER: hellodoctor-configserver

  rabbitmq-server:
    image: "rabbitmq:3-management"
    hostname: rabbitmq-server
    networks:
      - hellodoctor-network
    ports:
      - 5000:15672
      - 500:5672

  zipkin-server:
    image: openzipkin/zipkin
    networks:
      - hellodoctor-network
    ports:
      - 9411:9411
    environment:
      RABBIT_ADDRESSES: rabbitmq-server

networks:
  hellodoctor-network: