# Name of the Application
spring:
  zipkin:
    baseUrl: http://localhost:9411
  application:
    name: hellodoctor-test-service

# Port of the Server
server:
  port: 8082
eureka:
  client:
    serviceUrl:
      defaultZone:
        http://localhost:8761/eureka/